### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by GenieCloud** [ohub-floss-atl/prizes#10]
**Please describe what you did**

I successfully installed Github Desktop, Atom Text Editor, Visual Studio Code and Microsoft VSCode Plugin for Github Pull Requests :)

**Link to repo**
[link goes here](/)

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_
![vscode-desktop](https://user-images.githubusercontent.com/20313762/58749857-2f2dd780-8459-11e9-839d-77dcddf2ae1b.PNG)
![atom-desktop](https://user-images.githubusercontent.com/20313762/58749863-394fd600-8459-11e9-815c-e1801e6e51a3.PNG)
![github-desktop](https://user-images.githubusercontent.com/20313762/58749871-3fde4d80-8459-11e9-8bb6-6b96a8b2128a.PNG)

**Comment by jamccree** [comment]
@GenieCloud Nice! Come to the GitHub table to claim your prize.
