### ISSUE TITLE
[Prize] abah-Words on the internet

### ISSUE THREAD

**Issue by bahaaGit** [ohub-floss-atl/prizes#11]
**Link to blog post**
[link goes here](/)
https://www.facebook.com/photo.php?fbid=2318315348489828&set=a.1683026258685410&type=3&theater

**Comment by jamccree** [comment]
👋 @bahaaGit Can you please post another link or provide a screenshot? I can't access the link you posted.

**Comment by bahaaGit** [comment]
Done!    On Saturday, June 1, 2019, 1:26:40 PM EDT, Jarryd McCree <notifications@github.com> wrote:  
 
 
👋 @bahaaGit Can you please post another link or provide a screenshot? I can't access the link you posted.

**Comment by bdougie** [comment]
Unfortunately, This is not a blog post. Can you write 500 words on a blog sharing your experience contributing to open source.

![](https://media.giphy.com/media/3og0IJXQEKwIdIEYpy/giphy.gif)
