### ISSUE TITLE
[Prize] issue bot

### ISSUE THREAD

**Issue by smithmanny** [ohub-floss-atl/prizes#12]
**Link to repo**
[Repo](https://github.com/smithmanny/probot-example)

**Note**
Basic Probot app that adds comments to new issues submitted by the current user.

**Comment by smithmanny** [comment]
Still working on it

**Comment by bdougie** [comment]
Nice, @smithmanny can you make the app do something anything else? 

https://developer.github.com/webhooks/#events

**Comment by bdougie** [comment]
@smithmanny please claim within the next 20mins, before we have to provide it to the next person

**Comment by bdougie** [comment]
claimed
