### ISSUE TITLE
[Prize] Localhost Github Desktop

### ISSUE THREAD

**Issue by sabur7** [ohub-floss-atl/prizes#13]
**Please describe what you did**
Download Github Desktop.
Logged into Github.com via Github Desktop
Cloned prizes repo

**Link to repo**
[https://github.com/ohub-floss-atl/prizes](/)

**Screenshot**
<img width="964" alt="github_desktop_running_locally" src="https://user-images.githubusercontent.com/4614385/58750157-be88ba00-845c-11e9-8e95-53254cae625b.png">
<img width="1680" alt="project_running_in_terminal" src="https://user-images.githubusercontent.com/4614385/58750171-eb3cd180-845c-11e9-856a-1b5410e4e103.png">

**Comment by jamccree** [comment]
@sabur7 Nice! Come to the GitHub table to claim your giftcard.

**Comment by bdougie** [comment]
already given out
