### ISSUE TITLE
[Prize] Localhost an editor(Atom)

### ISSUE THREAD

**Issue by coreyrshaw** [ohub-floss-atl/prizes#15]
**Please describe what you did**
I successfully installed Atom and was able to setup Github connection.

**Link to repo**
N/A. I use the following documentation for setup. https://github.atom.io/ 

**Installed Github Package**
<img width="1440" alt="Screen Shot 2019-06-01 at 10 57 35 AM" src="https://user-images.githubusercontent.com/18070513/58750127-386c7380-845c-11e9-87de-f7aae6ea1ca8.png">

**Successfully cloned project in Atom
<img width="1440" alt="Screen Shot 2019-06-01 at 11 07 10 AM" src="https://user-images.githubusercontent.com/18070513/58750215-833abb00-845d-11e9-8e9c-5ae9ac6f2032.png">
**

**Comment by jamccree** [comment]
@coreyrshaw Nice! Come to the GitHub table to claim your gift card.
