### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by kat89** [ohub-floss-atl/prizes#18]
**Please describe what you did**

-I've forked and git cloned desktop/desktop repo. I have downloaded Visual Studio Code and installed the Github vscode plugin.

**Link to repo**

https://github.com/kat89/desktop

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_

**Comment by bdougie** [comment]
@kat89 can you provide a screenshot?

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
