### ISSUE TITLE
Completed challenge for JBL Speakers

### ISSUE THREAD

**Issue by bwold001** [ohub-floss-atl/prizes#19]
**Please describe your change**

There was an issue where the documentation didn't match the code. Here's a link to the issue
https://github.com/rcaferati/react-native-really-awesome-button/issues/21

**Link to my pull request**
https://github.com/rcaferati/react-native-really-awesome-button/pull/22

**Comment by bdougie** [comment]
Nice! @bwold001 looking forward to seeing this merged. 

Please send your address and phone to blacktocats@github.com and provide a link to this issue.

**Comment by bwold001** [comment]
> Nice! @bwold001 looking forward to seeing this merged.
> 
> Please send your address and phone to [blacktocats@github.com](mailto:blacktocats@github.com) and provide a link to this issue.

Done ... thanks :)

**Comment by bdougie** [comment]
sorry this was for a JBL speaker. find me after the panel for the speaker
