### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by kat89** [ohub-floss-atl/prizes#20]
**Please describe what you did**
I have forked and git cloned Github Desktop repo, upgraded Visual Studio Code, and installed the Github pull request extension.

**Link to repo**
https://github.com/kat89/desktop

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_
![image](https://user-images.githubusercontent.com/18070716/58750429-605dd600-8460-11e9-8770-9f5d589df44e.png)

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
