### ISSUE TITLE
[Prize]localhost init GitHub Desktop

### ISSUE THREAD

**Issue by ysmith7** [ohub-floss-atl/prizes#22]
**Please describe what you did**

Downloaded GitHub Desktop  
Login Github.com via GHDesktop
Cloned repo

**Link to repo**
https://github.com/ohub-floss-atl/prizes

**Screenshot**
_
<img width="1198" alt="screenshot" src="https://user-images.githubusercontent.com/51265659/58750491-51c3ee80-8461-11e9-9923-7cdcc75f0f43.png">

 _

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
