### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by getsthepicture** [ohub-floss-atl/prizes#23]
**Please describe what you did**
This one was low hanging fruit I believe because I've experienced downloading extensions in Visual Studio Code while working at the Department of Public Safety for the State of Georgia.  I stumbled while reading the prize instructions because I thought all I needed to do was install the extension through the marketplace but we were instructed to build and run the github repo.  There were a lot of little steps in the process but it wasn't hard because of the way I think of it.  For example, instead of clicking on a .exe file on my desktop, we usually run things from the command line so I figured this prize was purely an introduction to starting running applications from the command line while having a backup repo using GitHub.  My name is Laurence Wingo by the way.  Now that we've gone into the presentations here at the Hack Day, I'm realizing that GitHub is looking for more open source contributors for tools such as Visual Studio.
**Link to repo**
[https://github.com/cosmicarrows/desktop](/)

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_

![Screen Shot 2019-06-01 at 11 48 00 AM](https://user-images.githubusercontent.com/33186729/58750748-0ced8700-8464-11e9-9479-fdc088f278a9.png)
![Screen Shot 2019-06-01 at 11 54 27 AM](https://user-images.githubusercontent.com/33186729/58750749-0d861d80-8464-11e9-88b2-b0c4a1c92fb1.png)

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
