### ISSUE TITLE
[Prize] Creating a Probot Integration (lgtm Probot)

### ISSUE THREAD

**Issue by willmadison** [ohub-floss-atl/prizes#26]
**Link to repo**
https://github.com/willmadison/lgtm

**Note**
Once your PR is confirmed we will need follow up with instructions to send your t-shirt.

**Comment by bdougie** [comment]
Nice work, let see if you can deploy this to production: https://probot.github.io/docs/deployment/

**Comment by bdougie** [comment]
come by the table to claim your plushie or figurine

![](https://media.giphy.com/media/yxXlZ8LRB2UYU/giphy.gif)

**Comment by bdougie** [comment]
![](https://media.giphy.com/media/thNsW0HZ534DC/giphy.gif)

**Comment by willmadison** [comment]
Sorry just seeing this. We were able to get a plushie on the way out due to my daughter's cuteness lol

**Comment by bdougie** [comment]
excellent
