### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by coreyrshaw** [ohub-floss-atl/prizes#27]
**Please describe your change**
I added a Contribution header along with steps on how to contribute to this project.

**Link to pull request**
https://github.com/ohub-floss-atl/prizes/pull/25

**Comment by bdougie** [comment]
![](https://media.giphy.com/media/3og0IJXQEKwIdIEYpy/giphy.gif)

**Comment by bdougie** [comment]
This is meta, but can't provide this PR. Try again.
