### ISSUE TITLE
Completed challenge for Starbucks gift card

### ISSUE THREAD

**Issue by bwold001** [ohub-floss-atl/prizes#28]
**Please describe what you did**
Installed GitHub Desktop, Atom and Visual Studio GitHub plugin and got it working

**Link to repo**
[link goes here](/)

**Screenshot**
![image](https://user-images.githubusercontent.com/16202110/58751137-97d08080-8468-11e9-8868-421515eb6d60.png)

![image](https://user-images.githubusercontent.com/16202110/58751141-a880f680-8468-11e9-9261-c992aee81f18.png)

![image](https://user-images.githubusercontent.com/16202110/58751143-b0d93180-8468-11e9-9140-1b7b3c2fa005.png)

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
