### ISSUE TITLE
[Prize] Starbucks

### ISSUE THREAD

**Issue by kbennett30** [ohub-floss-atl/prizes#29]
**Please describe what you did**

**Link to repo**
[link goes here](/)

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
