### ISSUE TITLE
[Prize] 1 Local Editor

### ISSUE THREAD

**Issue by Taylor-McNeil** [ohub-floss-atl/prizes#3]
**Please describe what you did**
I installed Atom and Github Desktop. I already had VS Code and VS on my computer.

**Link to repo**
N/A

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_

![Atom](https://user-images.githubusercontent.com/20545092/58749704-26d49d00-8457-11e9-8bdf-749991dcd7dc.PNG)
![GHDesktop](https://user-images.githubusercontent.com/20545092/58749705-26d49d00-8457-11e9-983f-7cbdf047bfb0.PNG)
![VS Code](https://user-images.githubusercontent.com/20545092/58749706-26d49d00-8457-11e9-8c8e-62cdf78ac657.PNG)
![VS](https://user-images.githubusercontent.com/20545092/58749707-276d3380-8457-11e9-9d4e-836c29d72fa6.PNG)

**Comment by jamccree** [comment]
@Taylor-McNeil Nice! Come to the GitHub table to get your prize.
