### ISSUE TITLE
[Prize] Local Setup

### ISSUE THREAD

**Issue by smithmanny** [ohub-floss-atl/prizes#31]
**Please describe what you did**
Installed all applications and tools
**Link to repo**
[link goes here](/)

**Screenshot**
![Github Desktop](https://i.postimg.cc/SRD0bCTD/Screen-Shot-2019-06-01-at-1-19-22-PM.png)
![Atom](https://i.postimg.cc/90Sp9frc/Screen-Shot-2019-06-01-at-1-19-30-PM.png)
![VSCode](https://i.postimg.cc/cLfmK0ZN/Screen-Shot-2019-06-01-at-1-19-38-PM.png)
![Github VSCode Plugin](https://i.postimg.cc/fLymvN4y/Screen-Shot-2019-06-01-at-1-19-53-PM.png)

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)

....also your bot is infesting our repos -_-
