### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by ninibean** [ohub-floss-atl/prizes#32]
**Link to repo**
https://github.com/ninibean/picklesbot

**Note**
Once your PR is confirmed we will need follow up with instructions to send your t-shirt.

**Comment by bdougie** [comment]
Which prize are you claiming, what work was completed?

**Comment by ninibean** [comment]
I was claiming the figurine/ plushie!

I made a bot using probot that responds to the user opening and closing an issue

**Comment by bdougie** [comment]
Gotcha. come by the table to claim your plushie or figurine

![https://media.giphy.com/media/yxXlZ8LRB2UYU/giphy.gif](https://media.giphy.com/media/yxXlZ8LRB2UYU/giphy.gif)
