### ISSUE TITLE
[Prize] Github Desktop working locally

### ISSUE THREAD

**Issue by nijfranck** [ohub-floss-atl/prizes#33]
**Please describe what you did**
Cloned the github desktop repo: https://github.com/desktop/desktop
Run the setup commands to run it locally
> yarn
> yarn build:dev
> yarn start

**Link to repo**
[https://github.com/ohub-floss-atl/prizes](/)

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_

<img width="849" alt="desktop-yarn-build" src="https://user-images.githubusercontent.com/9940307/58751858-a2901300-8472-11e9-839d-15537ad89242.png">
<img width="1280" alt="desktop-launched-from-terminal" src="https://user-images.githubusercontent.com/9940307/58751859-a328a980-8472-11e9-8989-8a033c6f59cb.png">
<img width="1280" alt="yarn-start-running" src="https://user-images.githubusercontent.com/9940307/58751860-a328a980-8472-11e9-97f6-911060c72799.png">

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
