### ISSUE TITLE
getting GitHub running locally ( [Prize] Starbucks gift card)

### ISSUE THREAD

**Issue by tuyiskevin** [ohub-floss-atl/prizes#34]
**Please describe what you did**
With VScode already installed, I installed GitHub plugin then cloned a git project and run it on the computer. 
**Link to repo**

https://github.com/mitcc/AlgoSolutions

**Screenshot**
<img width="1440" alt="Screen Shot 2019-06-01 at 2 01 17 PM" src="https://user-images.githubusercontent.com/46584393/58752025-e20c2e80-8475-11e9-961d-5a6165d879fd.png">

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
