### ISSUE TITLE
[Prize] Words on the internet

### ISSUE THREAD

**Issue by bahaaGit** [ohub-floss-atl/prizes#35]
**Link to blog post**
 abah-Words on the internet
<img width="1028" alt="Screen Shot 2019-06-01 at 2 33 50 PM" src="https://user-images.githubusercontent.com/12416227/58752295-77112680-847a-11e9-9a87-7aa267c067f2.png">

**Comment by bdougie** [comment]
Need a blog post

> Blog post sharing your experience at FLOSS and Code within 3-days of the event
