### ISSUE TITLE
[Prize] PR request for JBL speakers. 

### ISSUE THREAD

**Issue by nijfranck** [ohub-floss-atl/prizes#36]
**Please describe your change**
Machine learning resources (https://github.com/datascienceid/machine-learning-resources) is a repo that contains different ML resources but unfortunately, it lacked one of the most prominent and popular course in the domain, which is the Fast AI Deep Learning for coders. I made a PR to add it to the list of courses.

**Link to pull request**
[https://github.com/datascienceid/machine-learning-resources/pull/6](/)

**Comment by bdougie** [comment]
not quite what we are looking for
