### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by rcooper47** [ohub-floss-atl/prizes#37]
![Screenshot 2019-06-01 14 42 33](https://user-images.githubusercontent.com/48736236/58752407-5649d080-847c-11e9-9df8-25729da3544d.png)
![Screenshot 2019-06-01 14 44 27](https://user-images.githubusercontent.com/48736236/58752408-5649d080-847c-11e9-8575-5a7ef336b221.png)
![Screenshot 2019-06-01 14 47 32](https://user-images.githubusercontent.com/48736236/58752409-5649d080-847c-11e9-9aee-28dbb6e4fc88.png)
![Screenshot 2019-06-01 14 48 03](https://user-images.githubusercontent.com/48736236/58752410-5649d080-847c-11e9-9450-23a9473bd85d.png)

Finished: Get GitHub Desktop, Atom, Microsoft VSCode, Visual Studio Code working locally.

**Comment by bdougie** [comment]
Unfortunately, All cards have been claimed. Keep Hacking!!!!

![](https://media.giphy.com/media/MnpMnpxpj4soBm4man/giphy.gif)
