### ISSUE TITLE
[Prize] Opened PR

### ISSUE THREAD

**Issue by baldhead403** [ohub-floss-atl/prizes#39]
https://github.com/JS-goose/heart-track/pull/11

**Link to blog post**
_provide the link to the PR_

**Note**
Once your PR is confirmed we will need to follow up with instructions to send your hoodie.

**Comment by bdougie** [comment]
Looks like we all attempted to fix the same problem. Look into other projects and keep FLOSSin

![](https://media.giphy.com/media/vw5sWbe5xs0Le/giphy.gif)
