### ISSUE TITLE
[Prize] 1 VScode and github Desktop

### ISSUE THREAD

**Issue by bahaaGit** [ohub-floss-atl/prizes#4]
**Please describe what you did**

Downloaded the  GitHub desktop app from GitHub downloads
Already had VScode, when to the extension tab and got the git hub plugin. Attached is a screenshot 

<img width="926" alt="Screen Shot 2019-06-01 at 10 12 57 AM" src="https://user-images.githubusercontent.com/12416227/58749596-f6d8ca00-8455-11e9-8a30-a57942cb1c1f.png">

<img width="926" alt="Screen Shot 2019-06-01 at 10 10 02 AM" src="https://user-images.githubusercontent.com/12416227/58749604-00fac880-8456-11e9-9b32-b52347562a75.png">

<img width="803" alt="Screen Shot 2019-06-01 at 10 19 31 AM" src="https://user-images.githubusercontent.com/12416227/58749667-d0fff500-8456-11e9-8fb3-3d173d7f7d44.png">

**Comment by jamccree** [comment]
@bahaaGit Nice! Come to the GitHub table to claim your prize.
