### ISSUE TITLE
[Prize] Henry Moses Official Prize for JBL

### ISSUE THREAD

**Issue by henrymoses21** [ohub-floss-atl/prizes#40]
**Please describe your change**
I simply added my location to the mlh-localhost locations. 

**Link to pull request**
https://github.com/ohub-floss-atl/mlh-localhost-github/pull/18

**Comment by henrymoses21** [comment]
@bdougie

**Comment by bdougie** [comment]
This is code from the workshop @arelia and not an issue closed. Focus on solving existing issues
