### ISSUE TITLE
 JBL

### ISSUE THREAD

**Issue by henrymoses21** [ohub-floss-atl/prizes#41]
**Please describe your change**
Deleted resources file 

**Link to pull request**
https://github.com/dracula/dracula-theme/pull/323

**Comment by bdougie** [comment]
@henrymoses21 Improve the description! It doesn't describe what you did or link to the issue you are fixing.

**Comment by henrymoses21** [comment]
@bdougie done

**Comment by bdougie** [comment]
@henrymoses21 come through and grab a jbl
