### ISSUE TITLE
[Documentation PR]

### ISSUE THREAD

**Issue by bahaaGit** [ohub-floss-atl/prizes#42]
**Please describe your change**

I'm always frustrated when I look up a  solution to a programming problem or CS notes on a topic and I am routed to a GitHub page with a solution but headings only written Chinese.

This opensource repo has leetcode problem solutions and other CS topic some of which references documents in English. The Readme was in Chinese but I have appended translations next to the Chinese letters using google translate

**Link to pull request**
https://github.com/CyC2018/CS-Notes/pull/718

**Comment by bdougie** [comment]
com claim your jbl
