### ISSUE TITLE
[Prize] Successful merge

### ISSUE THREAD

**Issue by noelledusahel** [ohub-floss-atl/prizes#44]
Blog Post: https://www.linkedin.com/pulse/open-source-everything-noelle-barber

PR: https://github.com/desktop/desktop/pull/7662

**Note**
Once your PR is confirmed we will need to follow up with instructions to send your hoodie.

**Comment by bdougie** [comment]
Congrats on the merge. Despite this not being merged, I would still like to send you a Hoodie. Please send an email to blacktocats@github.com for your hoodie

name
address
phone number 
link to this issue
size 

![](https://media.giphy.com/media/SnsSGSQsBO2rK/giphy.gif)
