### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by noelledusahel** [ohub-floss-atl/prizes#45]
**Please describe your change**
For Github Desktop README.md does not display the default description 

Solution: Include description in the list of arguments, the writeDefaultReadme.
Left description argument as an optional argument in the writeDefaultReadme Component
**Link to pull request**
[link goes here](https://github.com/desktop/desktop/pull/7662)

**Comment by bdougie** [comment]
Nice job, look forward to seeing #35 get merged! I would love to send you a hoodie, please consider writing a blog post on your experience as well.

![](https://media.giphy.com/media/7J26LFeEuZRcr0esqU/giphy.gif)
