### ISSUE TITLE
[Prize] Documentation Pull Request

### ISSUE THREAD

**Issue by coreyrshaw** [ohub-floss-atl/prizes#46]
**Please describe your change**
I came a really cool project https://github.com/mathieudutour/medium-to-own-blog.
Viewing the documentation, I noticed that the update_article task was missing.
After cloning and running the app, I was able to successfully able to complete the update article feature. I've provided the steps in docs/ReadME.md .

**Link to pull request**
https://github.com/mathieudutour/medium-to-own-blog/pull/26

**Comment by bdougie** [comment]
Nice job! 

![](https://media.giphy.com/media/7J26LFeEuZRcr0esqU/giphy.gif)
