### ISSUE TITLE
Hoodie Challenge

### ISSUE THREAD

**Issue by bwold001** [ohub-floss-atl/prizes#47]
**Link to blog post**
_provide the link to the PR_
https://github.com/frescobaldi/frescobaldi/issues/932

**Comment by bdougie** [comment]
Congrats on the PRs. Despite this not being merged, I would still like to send you a Hoodie. Please send an email to blacktocats@github.com for your hoodie

name
address
phone number 
link to this issue
size 

![](https://media.giphy.com/media/SnsSGSQsBO2rK/giphy.gif)
