### ISSUE TITLE
JBL Speakers Challenge

### ISSUE THREAD

**Issue by bwold001** [ohub-floss-atl/prizes#48]
**Please describe your change**
There was an error in the documentation of how to use a certain function.

**Link to pull request**
https://github.com/bwold001/django-push/pull/1

**Comment by bdougie** [comment]
Thanks for FLOSSing. We have given out all speakers but please keep contributing to Open Source!

![](https://media.giphy.com/media/KD7kZWYmawHUb9LEZs/giphy.gif)
