### ISSUE TITLE
[Prize] Words on the internet

### ISSUE THREAD

**Issue by ninibean** [ohub-floss-atl/prizes#49]
**Link to blog post**
https://www.linkedin.com/feed/update/urn:li:activity:6541023415325777920/

I know you guys said no linkedin posts but I don't own a blog and I worked really hard on my words!

**Comment by bdougie** [comment]
Thank you so much for writing this up @ninibean. Please send your address to the email blacktocats@github.com mentioning you would like to claim your GitHub t-shirt.
