### ISSUE TITLE
[Prize] Words on the internet

### ISSUE THREAD

**Issue by elmkin48** [ohub-floss-atl/prizes#50]
**Link to blog post**
https://medium.com/@ekinma99/ohub-floss-12965ee1348

**Comment by bdougie** [comment]
Please email blacktocats@github.com to also link this issue and let us know we owe you a shirt (let us know what size).

![](https://media.giphy.com/media/aGCuGPJZvz9IY/giphy.gif)

**Comment by bdougie** [comment]
Just realized your post is still in draft form. Can you flip that to publish when you get a chance? 

Can you also change the mention of the event name to be "FLOSS and Code hack day," minus the OHUB.

**Comment by elmkin48** [comment]
I published it now. I removed the OHUB from the article but it still shows in the link.
https://medium.com/@ekinma99/ohub-floss-code-12965ee1348?source=friends_link&sk=583d4e9cf654ce817842745a36340cc2

**Comment by bdougie** [comment]
thanks again
