### ISSUE TITLE
[Prize] Successful merge

### ISSUE THREAD

**Issue by elmkin48** [ohub-floss-atl/prizes#51]
**Link to blog post**
_provide the link to the PR_

**Note**https://github.com/JS-goose/heart-track/pull/14
Once your PR is confirmed we will need to follow up with instructions to send your hoodie.

**Comment by bdougie** [comment]
Congrats on the merge. Please send an email to blacktocats@github.com for your hoodie

address
phone number 
link to this issue
size 

![](https://media.giphy.com/media/SnsSGSQsBO2rK/giphy.gif)
