### ISSUE TITLE
[Prize] Words on the internet

### ISSUE THREAD

**Issue by JayDosunmu** [ohub-floss-atl/prizes#52]
**Link to blog post**
https://medium.com/@tjdosunmu/floss-and-code-working-together-to-build-something-better-2aa7c8f7ad32?source=friends_link&sk=080ddfb189a4b67cadcefc1bfc455f77

**Comment by bdougie** [comment]
Jay send us an email to blacktocats@github.com stating we owe you a shirt. 

We will need to know:

Address
phone number
size
link to this issues

![](https://media.giphy.com/media/aGCuGPJZvz9IY/giphy.gif)

**Comment by JayDosunmu** [comment]
@bdougie Hey Brian, is there a size chart I could take a look at? Sometimes these shirt sizes don't fit how I'd expect
