### ISSUE TITLE
[Prize] Successful bug fix PR merged

### ISSUE THREAD

**Issue by dbarochiya** [ohub-floss-atl/prizes#53]
**Link to blog post**
I have created a bug fix [PR](https://github.com/mathieudutour/medium-to-own-blog/pull/41) for this awsome project : [medium-to-own-blog](https://github.com/mathieudutour/medium-to-own-blog)  , which got accepted and merged into the codebase (It was the bug fix for the issue with parsing the link )
 
**Note**
Once your PR is confirmed we will need to follow up with instructions to send your hoodie.

**Comment by bdougie** [comment]
Congrats on the merge. Please send an email to blacktocats@github.com for your hoodie

name
address
phone number 
link to this issue
size 

![](https://media.giphy.com/media/SnsSGSQsBO2rK/giphy.gif)
