### ISSUE TITLE
[Prize] Provided useful resource 

### ISSUE THREAD

**Issue by dbarochiya** [ohub-floss-atl/prizes#54]
This (project)[https://github.com/mathieudutour/medium-to-own-blog] creates a personal blog based on the medium profile by importing the articles form medium and pushing them to the GitHub in markdown format which will be used by the parsers to create a webpage. 

When I was using the project codebase to create my personal blog, I noticed that for creating the new article I have to write in the markdown syntax ( which I am not very good at!!). I was able to found [this](https://ionicabizau.github.io/medium-editor-markdown/example/) service which provides the medium-like-editor and also converts the article into the markdown format on-the-fly. 

I discussed with the author of the repository and he suggested me to add the links related to this service in the project docs. I did and well ... the changes are now merged into the master

--
[doc update PR](https://github.com/mathieudutour/medium-to-own-blog/pull/42)

**Comment by bdougie** [comment]
Thanks for FLOSSing. We have given out all speakers but please keep contributing to Open Source!

![](https://media.giphy.com/media/KD7kZWYmawHUb9LEZs/giphy.gif)
