### ISSUE TITLE
[Prize] Words on the internet

### ISSUE THREAD

**Issue by sr98bj** [ohub-floss-atl/prizes#7]
**Link to blog post**
[https://www.linkedin.com/feed/update/urn:li:activity:6540594849689718784](/)

**Comment by jamccree** [comment]
👋 Hi @sr98bj.  Could you please post another link to the blog post? I can't seem to access the link above.

**Comment by sr98bj** [comment]
Ran through the setup instructions, had to install node, yarn and python and since its windows, had to install Visual Studio C++ Build Tools.  Got it working.
![google-desktop](https://user-images.githubusercontent.com/3828125/58752208-1e8d5980-8479-11e9-889c-2f7b4c38378b.PNG)

**Comment by sr98bj** [comment]
Posting the link again: https://www.linkedin.com/feed/update/urn:li:activity:6540594849689718784/

**Comment by sr98bj** [comment]
Yes - here's  the link: https://www.linkedin.com/feed/update/urn:li:activity:6540594849689718784/

**Comment by sr98bj** [comment]
> 👋 Hi @sr98bj. Could you please post another link to the blog post? I can't seem to access the link above.

https://www.linkedin.com/feed/update/urn:li:activity:6540594849689718784/

**Comment by bdougie** [comment]
Technically not a blog, need 500 words
