### ISSUE TITLE
[Prize]

### ISSUE THREAD

**Issue by sr98bj** [ohub-floss-atl/prizes#9]
**Please describe what you did**
I had to install node, python and yarn and also Visual Studio C++ Build tools, ran the yarn commands to get dependences, and build the project then launched it.

**Link to repo**
[https://github.com/sr98bj/desktop
![google-desktop](https://user-images.githubusercontent.com/3828125/58752219-60b69b00-8479-11e9-98c7-a06558ce5c01.PNG)
](/)

**Screenshot**
_Please provide a screenshot of the project running locally below. Please include GUI and terminal_

**Comment by sr98bj** [comment]
Installing Visual Studio Build Tools right now

**Comment by bdougie** [comment]
Need a screenshot showing you completed this

**Comment by bdougie** [comment]
claimed
